#!/bin/bash
#set -o errexit
#set -o pipefail
#set -o nounset
set -o xtrace

log=/home/ubuntu/power.log
echo "INFO: $(date) Suspend invoked by $(whoami) $0 $*" >> $log

hosts=`scontrol show hostnames $1`
for host in $hosts
do
    /usr/sbin/node_shutdown $host >> $log 2>&1 &
done
