---
- hosts: tag_slurmtype_master:tag_slurmtype_computenode
  remote_user: ubuntu
  roles:
    - slurm-common

- hosts: tag_slurmtype_master
  remote_user: ubuntu
  pre_tasks:
    - name: Install filesystem on xvdb
      become: yes
      filesystem: fstype=ext4 dev=/dev/xvdb
    - name: Create the shared directory
      become: yes
      file: path=/ppgdata owner=ubuntu group=ubuntu state=directory
    - name: Mount the volume at /ppgdata
      become: yes
      mount: name=/ppgdata state=mounted fstype=ext4 src=/dev/xvdb
  roles:
    - { role: nfs-server, nfsdir: /ppgdata }
    - slurm-master
    - notebook-access

- hosts: tag_slurmtype_computenode
  remote_user: ubuntu
  roles:
    - slurm-compute
