---
- hosts: localhost
  connection: local
  gather_facts: true
  tasks:
    - name: Provision master node
      ec2:
        key_name: slurmkey
        group: WebServerSG
        instance_type: t2.medium
        image: ami-d05e75b8
        wait: true
        private_ip: 10.0.0.4
        instance_tags: 
          Name: masternode
          slurmtype: master
        count_tag: 
          slurmtype: master
        exact_count: 1
        region: us-east-1
        vpc_subnet_id: subnet-dee89a87
        assign_public_ip: yes
        volumes:
          - device_name: /dev/xvdb
            volume_size: 500
            delete_on_temination: true
            device_type: standard
      register: ec2_masters
    - name: Wait for ssh to come up on the master node
      wait_for: host={{ item.public_dns_name }} port=22 delay=2 timeout=320 state=started
      with_items: ec2_masters.tagged_instances

    # - name: Provision compute nodes
    #   ec2:
    #     key_name: slurmkey
    #     group: WebServerSG
    #     instance_type: t2.medium
    #     image: ami-d05e75b8
    #     wait: true
    #     instance_tags:
    #       Name: computenode
    #       slurmtype: compute
    #     count_tag: 
    #       slurmtype: compute
    #     exact_count: 0
    #     # spot_price: 0.08
    #     # spot_wait_timeout: 3600
    #     region: us-east-1
    #     vpc_subnet_id: subnet-dee89a87
    #     assign_public_ip: yes
    #   register: ec2_computes
    # - name: Wait for ssh to come up
    #   wait_for: host={{ item.public_dns_name }} port=22 delay=2 timeout=320 state=started
    #   with_items: ec2_computes.tagged_instances
